runs:
  using: "composite"
  steps: 
      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash
      
      # increase to reset cache manually
      - name: Set cache number
        run: echo "CACHE_NUMBER=0" >> $GITHUB_ENV 
        shell: bash

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: latest

      - name: Create minimal Python 3.10 environment and install uv
        run: |
          pixi init python=3.10 --name mixtera
          pixi add uv -n mixtera
        shell: bash

      - name: Install project with uv
        run: |
          pixi run -e mixtera uv pip install -e .[dev,torch]
        shell: bash
