name: mixtera

channels:
  - conda-forge
  - anaconda
  - pytorch

dependencies:
  - python==3.11
  - pip
  - tqdm
  - loguru
  - numpy
  - dill
  - portion
  - pytorch::pytorch # TODO(#9): We need proper packaging. This should be an optional dependency