name: linting-and-tests
on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  flake8:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: ./.github/actions/mamba

      - name: Flake8
        run: |
          pixi run -e mixtera flake8 --version
          pixi run -e mixtera flake8 mixtera --statistics

  mypy-typechecking:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: ./.github/actions/mamba

      - name: Mypy
        run: |
          pixi run -e mixtera mypy --version
          pixi run -e mixtera mypy mixtera

  pylint:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: ./.github/actions/mamba

      - name: Pylint
        run: |
          pixi run -e mixtera pylint --version
          pixi run -e mixtera pylint mixtera

  isort:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: ./.github/actions/mamba

      - name: Isort
        run: |
          pixi run -e mixtera isort --version
          pixi run -e mixtera isort mixtera --check --diff
          pixi run -e mixtera isort integrationtests --check --diff

  black:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: ./.github/actions/mamba

      - name: Black
        run: |
          pixi run -e mixtera black --version
          pixi run -e mixtera black --check mixtera --verbose --config black.toml

  unittests:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: ./.github/actions/mamba

      - name: Pytest
        run: |
          pixi run -e mixtera pytest mixtera --cov-reset --cache-clear --cov-fail-under=90
          pixi run -e mixtera pytest > pytest-coverage.txt

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2

  integrationtests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs:
      - flake8
      - mypy-typechecking
      - pylint
      - unittests
      - isort
      - black

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup mamba
        uses: ./.github/actions/mamba

      - name: Run integrationtests
        run: pixi run -e mixtera bash integrationtests/run.sh